var jsonTableLocalText = {
    "search":"Arama...",
    "not_a_date":"Tarih Yok",
    "choose":"Seçim",
    "contains":"İçeren",
    "bigger_than":"Büyüktür",
    "smaller_than":"Küçüktür",
    "equals":"Eşittir",
    "between":"Arasında",
    "clear_filters":"Filtreleri Temizle",
    "all":"Tümü",
    "number_of_rows":"Satır Sayısı:",
    "number_of_shown_records":"Toplam %1 Kayıttan %2 Kayıt Gösteriliyor",
    "<empty>" : "<BOŞ>",
    "column" : "Sütun",
    "total" : "Toplam",
    "sum" : "Toplam",
    "min" : "Min.",
    "max" : "Max.",
    "avg" : "Ortalama",
    "count" : "Sayı",
    "percentage" : "Yüzde",
}